# Generated by Django 5.2.3 on 2025-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="student_id",
            field=models.IntegerField(null=True),
        ),
    ]
