# Generated by Django 5.2.3 on 2025-07-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_student_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="lastname",
            new_name="email",
        ),
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
            preserve_default=False,
        ),
    ]
