# Generated by Django 5.2.3 on 2025-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=255)),
                ("Last_Name", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255)),
                ("Phone", models.BigIntegerField()),
            ],
        ),
    ]
