# Generated by Django 5.2.3 on 2025-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JCU_Gym", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00-10:00", "09:00 - 10:00"),
                            ("10:00-11:00", "10:00 - 11:00"),
                            ("11:00-12:00", "11:00 - 12:00"),
                            ("12:00-13:00", "12:00 - 13:00"),
                            ("13:00-14:00", "13:00 - 14:00"),
                            ("14:00-15:00", "14:00 - 15:00"),
                            ("15:00-16:00", "15:00 - 16:00"),
                            ("16:00-17:00", "16:00 - 17:00"),
                            ("17:00-18:00", "17:00 - 18:00"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="Phone",
            field=models.CharField(max_length=20),
        ),
    ]
